export function inferCodeLanguageFromPath(filePath: string): string {
  const filename = filePath.split('/').filter(Boolean).at(-1)?.toLowerCase() ?? ''
  const ext = filename.split('.').pop() ?? ''

  if (filename === 'dockerfile' || filename.endsWith('.dockerfile')) return 'dockerfile'
  if (filename === 'docker-compose.yml' || filename === 'docker-compose.yaml' || filename === 'compose.yml' || filename === 'compose.yaml') return 'yaml'
  if (filename === 'makefile' || filename === 'gnumakefile') return 'makefile'
  if (filename === 'cmakelists.txt') return 'cmake'
  if (filename === 'nginx.conf') return 'nginx'
  if (filename === 'apache.conf' || filename === 'httpd.conf') return 'apache'
  if (filename === '.env' || filename.startsWith('.env.')) return 'dotenv'
  if (filename === '.gitmodules') return 'ini'

  const map: Record<string, string> = {
    apacheconf: 'apache',
    astro: 'astro',
    bash: 'shellscript',
    bat: 'batch',
    c: 'c',
    cjs: 'javascript',
    cc: 'cpp',
    clj: 'clojure',
    cmake: 'cmake',
    cmd: 'cmd',
    conf: 'ini',
    cpp: 'cpp',
    cs: 'csharp',
    cts: 'typescript',
    csv: 'csv',
    css: 'css',
    dart: 'dart',
    diff: 'diff',
    dockerfile: 'dockerfile',
    dotenv: 'dotenv',
    eex: 'elixir',
    erl: 'erlang',
    ex: 'elixir',
    exs: 'elixir',
    graphql: 'graphql',
    go: 'go',
    gradle: 'groovy',
    groovy: 'groovy',
    h: 'c',
    hs: 'haskell',
    hpp: 'cpp',
    html: 'html',
    http: 'http',
    ini: 'ini',
    java: 'java',
    js: 'javascript',
    json: 'json',
    json5: 'json5',
    jsonc: 'jsonc',
    jsx: 'jsx',
    kt: 'kotlin',
    kts: 'kotlin',
    less: 'less',
    log: 'log',
    lua: 'lua',
    m: 'matlab',
    make: 'makefile',
    md: 'markdown',
    mmd: 'mermaid',
    mdx: 'markdown',
    mermaid: 'mermaid',
    mjs: 'javascript',
    ml: 'ocaml',
    mli: 'ocaml',
    mts: 'typescript',
    nginxconf: 'nginx',
    patch: 'diff',
    pl: 'perl',
    php: 'php',
    properties: 'properties',
    proto: 'proto',
    ps1: 'powershell',
    psd1: 'powershell',
    psm1: 'powershell',
    py: 'python',
    r: 'r',
    rb: 'ruby',
    rs: 'rust',
    scala: 'scala',
    scss: 'scss',
    sh: 'shellscript',
    svelte: 'svelte',
    svg: 'xml',
    sql: 'sql',
    swift: 'swift',
    tf: 'terraform',
    toml: 'toml',
    ts: 'typescript',
    tsx: 'tsx',
    vue: 'vue',
    xml: 'xml',
    yaml: 'yaml',
    yml: 'yaml',
    zig: 'zig',
    zsh: 'shellscript',
  }

  return map[ext] ?? 'text'
}
