import { useState } from 'react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import { browserRuntime } from '@/lib/desktop-api'
import type { BrowserExtensionDescriptor } from '@lume/shared'

type Password = { id: string; origin: string; username: string }
type Contact = { id: string; label: string; fields: string[] }
type Download = { id: string; filename: string; actor: 'user' | 'agent'; state: string; receivedBytes: number; createdAt: string }
type HistoryEntry = { id: string; url: string; title: string; visitedAt: string }

export function BrowserDataManagers({ onImport }: { onImport: () => void }) {
  const [dialog, setDialog] = useState<'passwords' | 'contacts' | 'downloads' | 'history' | 'extensions' | 'clear' | null>(null)
  const [passwords, setPasswords] = useState<Password[]>([])
  const [contacts, setContacts] = useState<Contact[]>([])
  const [downloads, setDownloads] = useState<Download[]>([])
  const [history, setHistory] = useState<HistoryEntry[]>([])
  const [extensions, setExtensions] = useState<BrowserExtensionDescriptor[]>([])
  const [historyQuery, setHistoryQuery] = useState('')
  const [contact, setContact] = useState({ label: '', name: '', email: '', phone: '', address: '' })
  const [clearCategories, setClearCategories] = useState({ siteData: true, cache: true, history: true, downloads: true, permissions: false, passwords: false })
  const [timeRange, setTimeRange] = useState<'hour' | 'day' | 'all'>('all')

  const open = (kind: typeof dialog) => {
    setDialog(kind)
    if (kind === 'passwords') void browserRuntime<Password[]>({ method: 'vault:list-passwords' }).then(setPasswords)
    if (kind === 'contacts') void browserRuntime<Contact[]>({ method: 'contacts:list' }).then(setContacts)
    if (kind === 'downloads') void browserRuntime<Download[]>({ method: 'downloads:list' }).then(setDownloads)
    if (kind === 'history') void loadHistory('')
    if (kind === 'extensions') void browserRuntime<BrowserExtensionDescriptor[]>({ method: 'extensions:list' }).then(setExtensions)
  }
  const loadHistory = (query: string) => browserRuntime<HistoryEntry[]>({ method: 'history:list', params: { query, limit: 500 } }).then(setHistory).catch(() => toast.error('历史记录读取失败'))
  const saveContact = () => void browserRuntime<Contact>({ method: 'contacts:upsert', params: contact }).then((saved) => { setContacts((items) => [...items.filter((item) => item.id !== saved.id), saved]); setContact({ label: '', name: '', email: '', phone: '', address: '' }); toast.success('联系信息已加密保存') }).catch(() => toast.error('联系信息保存失败'))
  const clear = () => {
    const categories = Object.entries(clearCategories).filter(([, checked]) => checked).map(([key]) => key)
    void browserRuntime({ method: 'clear-data', params: { categories, timeRange } }).then(() => { toast.success('所选 Lume 浏览数据已清除'); setDialog(null) }).catch(() => toast.error(timeRange === 'all' ? '清理失败' : 'Cookie、站点数据和缓存目前只支持“全部时间”；下载记录支持时间范围'))
  }

  return <>
    <div className="mt-2 flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => open('passwords')}>密码管理</Button><Button variant="outline" size="sm" onClick={() => open('contacts')}>联系人管理</Button><Button variant="outline" size="sm" onClick={() => open('history')}>浏览历史</Button><Button variant="outline" size="sm" onClick={() => open('downloads')}>下载历史</Button><Button variant="outline" size="sm" onClick={() => open('extensions')}>本地扩展</Button><Button variant="outline" size="sm" onClick={() => open('clear')}>清除浏览数据</Button><Button variant="outline" size="sm" onClick={onImport}>导入 Cookie 和密码…</Button></div>

    <Dialog open={dialog === 'passwords'} onOpenChange={(value) => !value && setDialog(null)}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>密码管理器</DialogTitle><DialogDescription>仅显示来源和用户名；Lume 不在设置页展示或复制密码明文。</DialogDescription></DialogHeader><div className="max-h-72 space-y-2 overflow-auto">{passwords.length ? passwords.map((entry) => <div key={entry.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><div className="min-w-0"><div className="truncate text-sm font-medium">{entry.username}</div><div className="truncate text-xs text-muted-foreground">{entry.origin}</div></div><Button variant="destructive" size="sm" onClick={() => void browserRuntime({ method: 'vault:delete-password', params: { id: entry.id } }).then(() => setPasswords((items) => items.filter((item) => item.id !== entry.id)))}>删除</Button></div>) : <div className="py-8 text-center text-sm text-muted-foreground">尚无保存的密码</div>}</div></DialogContent></Dialog>

    <Dialog open={dialog === 'contacts'} onOpenChange={(value) => !value && setDialog(null)}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>联系信息</DialogTitle><DialogDescription>姓名、地址、电话和邮箱使用系统安全存储加密。</DialogDescription></DialogHeader><div className="grid gap-2 sm:grid-cols-2"><Input placeholder="标签（必填）" value={contact.label} onChange={(event) => setContact({ ...contact, label: event.target.value })} /><Input placeholder="姓名" value={contact.name} onChange={(event) => setContact({ ...contact, name: event.target.value })} /><Input placeholder="邮箱" value={contact.email} onChange={(event) => setContact({ ...contact, email: event.target.value })} /><Input placeholder="电话" value={contact.phone} onChange={(event) => setContact({ ...contact, phone: event.target.value })} /><Input className="sm:col-span-2" placeholder="地址" value={contact.address} onChange={(event) => setContact({ ...contact, address: event.target.value })} /></div><Button disabled={!contact.label.trim()} onClick={saveContact}>添加联系信息</Button><div className="max-h-48 space-y-2 overflow-auto">{contacts.map((entry) => <div key={entry.id} className="flex items-center justify-between rounded-lg border p-3"><div><div className="text-sm font-medium">{entry.label}</div><div className="text-xs text-muted-foreground">已保存：{entry.fields.join('、')}</div></div><Button variant="destructive" size="sm" onClick={() => void browserRuntime({ method: 'contacts:delete', params: { id: entry.id } }).then(() => setContacts((items) => items.filter((item) => item.id !== entry.id)))}>删除</Button></div>)}</div></DialogContent></Dialog>

    <Dialog open={dialog === 'downloads'} onOpenChange={(value) => !value && setDialog(null)}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>下载历史</DialogTitle><DialogDescription>历史只包含文件名、状态和非敏感引用，不保存完整路径。</DialogDescription></DialogHeader><div className="max-h-72 space-y-2 overflow-auto">{downloads.length ? downloads.map((entry) => <div key={entry.id} className="rounded-lg border p-3"><div className="truncate text-sm font-medium">{entry.filename}</div><div className="text-xs text-muted-foreground">{entry.actor === 'agent' ? 'Agent' : '用户'} · {entry.state} · {new Date(entry.createdAt).toLocaleString()}</div></div>) : <div className="py-8 text-center text-sm text-muted-foreground">没有下载记录</div>}</div><DialogFooter><Button variant="destructive" disabled={!downloads.length} onClick={() => void browserRuntime({ method: 'downloads:clear' }).then(() => setDownloads([]))}>清除历史</Button></DialogFooter></DialogContent></Dialog>

    <Dialog open={dialog === 'history'} onOpenChange={(value) => !value && setDialog(null)}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>浏览历史</DialogTitle><DialogDescription>历史保存在本机；Agent 查询时会再次请求授权。</DialogDescription></DialogHeader><div className="flex gap-2"><Input value={historyQuery} onChange={(event) => setHistoryQuery(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void loadHistory(historyQuery) }} placeholder="搜索标题或网址" /><Button variant="outline" onClick={() => void loadHistory(historyQuery)}>搜索</Button></div><div className="max-h-80 space-y-2 overflow-auto">{history.length ? history.map((entry) => <div key={entry.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><div className="min-w-0"><div className="truncate text-sm font-medium">{entry.title || entry.url}</div><div className="truncate text-xs text-muted-foreground">{entry.url}</div><div className="text-xs text-muted-foreground">{new Date(entry.visitedAt).toLocaleString()}</div></div><Button variant="ghost" size="sm" onClick={() => void browserRuntime({ method: 'history:delete', params: { id: entry.id } }).then(() => setHistory((items) => items.filter((item) => item.id !== entry.id)))}>删除</Button></div>) : <div className="py-8 text-center text-sm text-muted-foreground">没有匹配的历史记录</div>}</div><DialogFooter><Button variant="destructive" disabled={!history.length} onClick={() => void browserRuntime({ method: 'history:clear' }).then(() => setHistory([]))}>清除全部历史</Button></DialogFooter></DialogContent></Dialog>

    <Dialog open={dialog === 'extensions'} onOpenChange={(value) => !value && setDialog(null)}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>本地浏览器扩展</DialogTitle><DialogDescription>只支持你选择并确认的 unpacked 扩展，仅加载到用户 Profile，不会进入 Agent 隔离 Profile。</DialogDescription></DialogHeader><div className="max-h-80 space-y-2 overflow-auto">{extensions.length ? extensions.map((extension) => <div key={extension.id} className="rounded-lg border p-3"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-medium">{extension.name} <span className="font-normal text-muted-foreground">{extension.version}</span></div><div className="mt-1 line-clamp-2 text-xs text-muted-foreground">{extension.permissions.length ? extension.permissions.join('、') : '未声明额外权限'}</div></div><div className="flex items-center gap-2"><Switch checked={extension.enabled} onCheckedChange={(enabled) => void browserRuntime<BrowserExtensionDescriptor>({ method: 'extensions:set-enabled', params: { id: extension.id, enabled } }).then((updated) => setExtensions((items) => [...items.filter((item) => item.id !== extension.id), updated])).catch(() => toast.error('扩展状态更新失败'))} /><Button variant="ghost" size="sm" onClick={() => void browserRuntime<{ removed: boolean }>({ method: 'extensions:remove', params: { id: extension.id } }).then(() => setExtensions((items) => items.filter((item) => item.id !== extension.id)))}>移除</Button></div></div></div>) : <div className="py-8 text-center text-sm text-muted-foreground">尚未安装本地扩展</div>}</div><DialogFooter><Button onClick={() => void browserRuntime<BrowserExtensionDescriptor | { canceled: true }>({ method: 'extensions:install' }).then((result) => { if ('canceled' in result) return; setExtensions((items) => [...items.filter((item) => item.id !== result.id), result]) }).catch(() => toast.error('本地扩展安装失败'))}>选择 unpacked 扩展…</Button></DialogFooter></DialogContent></Dialog>

    <Dialog open={dialog === 'clear'} onOpenChange={(value) => !value && setDialog(null)}><DialogContent><DialogHeader><DialogTitle>清除浏览数据</DialogTitle><DialogDescription>只影响 Lume。保存密码默认不选中，删除时还会出现系统级二次确认。</DialogDescription></DialogHeader><Select value={timeRange} onValueChange={(value) => setTimeRange(value as typeof timeRange)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="hour">过去一小时（仅下载记录）</SelectItem><SelectItem value="day">过去一天（仅下载记录）</SelectItem><SelectItem value="all">全部时间</SelectItem></SelectContent></Select>{Object.entries({ siteData: 'Cookie 和站点数据', cache: '缓存', history: '浏览历史', downloads: '下载记录', permissions: '站点权限', passwords: '保存的密码' }).map(([key, label]) => <label key={key} className="flex items-center gap-3 rounded-lg border p-3 text-sm"><Checkbox checked={clearCategories[key as keyof typeof clearCategories]} disabled={timeRange !== 'all' && key !== 'downloads'} onCheckedChange={(checked) => setClearCategories((current) => ({ ...current, [key]: checked === true }))} />{label}</label>)}<DialogFooter><Button variant="outline" onClick={() => setDialog(null)}>取消</Button><Button variant="destructive" onClick={clear}>清除</Button></DialogFooter></DialogContent></Dialog>
  </>
}
