import { atom } from 'jotai';
import { atomWithStorage } from 'jotai/utils';
export const agentThreadsAtom = atom([]);
export const currentThreadIdAtom = atom(null);
export const agentSDKMessagesAtom = atom({});
export const agentStreamingStatesAtom = atom({});
export const agentRuntimeStatusAtom = atom({});
export const agentPendingInteractiveAtom = atom({});
export const agentSubagentRunsAtom = atom({});
export const agentPlanStateAtom = atom({});
export const agentErrorMessagesAtom = atom({});
export const agentSidePanelViewAtom = atomWithStorage('agent-side-panel-view', {});
